name: bigwebthing
version: 0.0.0
synopsis: A programming language and interpreter for creating programmable documents.
maintainer: True Ghiassi <true@ghiassitrio.co.uk>
license: MIT

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - scotty
  - text
  - websockets

executables:
  server:
    main: Server.hs
    source-dirs: . 
    ghc-options: -Wall -threaded -main-is Server
  client:
    main: Client.hs
    source-dirs: .
    ghc-options: -Wall -threaded -main-is Client
  
