name:                clienth
version:             0.1.0.0
github:              "githubuser/clienth"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/clienth#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- text
- cacophony
- bytestring
- memory

ghc-options:
- -Weverything
- -Wno-missing-safe-haskell-mode
- -Wno-prepositive-qualified-module
- -Wno-implicit-prelude
- -Wno-unsafe
- -Wno-safe

library:
  source-dirs: src

executables:
  clienth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  clienth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clienth
