name:                server

dependencies:
- base >= 4.7 && < 5
- foundation
- stm
- cacophony
- memory
- sqlite-simple
- network-simple
- containers
- bytestring
- cryptonite
- attoparsec
- base64
- text

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Weverything
    - -Wno-prepositive-qualified-module
    - -Wno-missing-safe-haskell-mode
    - -Wno-safe
    - -Wno-unsafe
    - -Wno-missing-import-lists
    - -Wno-missing-deriving-strategies
