name:                server

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Weverything
- -Wno-prepositive-qualified-module
- -Wno-unsafe
- -Wno-safe
- -Wno-missing-safe-haskell-mode
- -Wno-implicit-prelude
- -Wno-monomorphism-restriction
- -Wno-missing-deriving-strategies
- -Wno-missing-import-lists
- -Werror

library:
  source-dirs: src
  dependencies:
  - bytestring
  - attoparsec
  - text
  - containers
  - network-simple
  - cryptonite
  - hex-text
  - memory
  - sqlite-simple
  - base64-bytestring

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stm
    - filepath
    - bytestring
    - text
    - network-simple
    - cryptonite
    - sqlite-simple
    - server

tests:
  server-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hedgehog
    - hedgehog
    - server
    - network
    - network-simple
    - cryptonite
    - containers
    - bytestring
