name:                serverh
version:             0.1.0.0
github:              "githubuser/serverh"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/serverh#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- bytestring
- cacophony
- memory
- network-simple
- containers
- text
- attoparsec
- sqlite-simple

ghc-options:
- -Weverything
- -Wno-prepositive-qualified-module
- -Wno-unsafe
- -Wno-missing-safe-haskell-mode
- -Wno-implicit-prelude
- -Wno-safe
- -Wno-missing-deriving-strategies

executables:
  serverh-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
